version: "3.8"

services:
    # Golang Application
    # app:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     container_name: golang_app
    #     ports:
    #         - "8080:8080"
    #     environment:
    #         - APP_ENV=development
    #         - APP_PORT=8080
    #         - APP_JWT_SECRET=0199feec-c0ad-78d2-8e96-75af55cbbf38
    #         - DB_HOST=postgres
    #         - DB_PORT=5432
    #         - DB_USER=root
    #         - DB_PASSWORD=root
    #         - DB_NAME=project_app_db
    #         - REDIS_HOST=redis
    #         - REDIS_PORT=6379
    #     depends_on:
    #         postgres:
    #             condition: service_healthy
    #         redis:
    #             condition: service_healthy
    #     networks:
    #         - project-app-network
    #     restart: unless-stopped

    # PostgreSQL Database
    postgres:
        image: postgres:18-alpine
        container_name: warehouse_management_db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=warehouse_management_app_db
        volumes:
            - warehouse_management_postgres_data:/var/lib/postgresql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U root -d warehouse_management_app_db"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - warehouse-management-app-network
        restart: unless-stopped

    # Redis Cache
    redis:
        image: redis:alpine3.22
        container_name: warehouse_management_cache
        command: redis-server --appendonly yes
        volumes:
            - warehouse_management_redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - "6379:6379"
        networks:
            - warehouse-management-app-network
        restart: unless-stopped

# Networks
networks:
    warehouse-management-app-network:
        driver: bridge

# Volumes
volumes:
    warehouse_management_postgres_data:
        driver: local
    warehouse_management_redis_data:
        driver: local
